/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/authenticated/users'
import { Route as AuthenticatedSupadminRouteImport } from './routes/authenticated/supadmin'
import { Route as AuthenticatedNewRouteImport } from './routes/authenticated/new'
import { Route as AuthenticatedAppRouteImport } from './routes/authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/authenticated/admin'
import { Route as AuthenticatedSubmissionIdRouteImport } from './routes/authenticated/$submissionId'
import { Route as AuthenticatedSiteIndexRouteImport } from './routes/authenticated/site.index'
import { Route as AuthenticatedSiteFormsFormIdRouteImport } from './routes/authenticated/site.forms.$formId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/authenticated/users',
  path: '/authenticated/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupadminRoute = AuthenticatedSupadminRouteImport.update({
  id: '/authenticated/supadmin',
  path: '/authenticated/supadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/authenticated/new',
  path: '/authenticated/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/authenticated/app',
  path: '/authenticated/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/authenticated/admin',
  path: '/authenticated/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubmissionIdRoute =
  AuthenticatedSubmissionIdRouteImport.update({
    id: '/authenticated/$submissionId',
    path: '/authenticated/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSiteIndexRoute = AuthenticatedSiteIndexRouteImport.update({
  id: '/authenticated/site/',
  path: '/authenticated/site/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSiteFormsFormIdRoute =
  AuthenticatedSiteFormsFormIdRouteImport.update({
    id: '/authenticated/site/forms/$formId',
    path: '/authenticated/site/forms/$formId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/authenticated/$submissionId': typeof AuthenticatedSubmissionIdRoute
  '/authenticated/admin': typeof AuthenticatedAdminRoute
  '/authenticated/app': typeof AuthenticatedAppRoute
  '/authenticated/new': typeof AuthenticatedNewRoute
  '/authenticated/supadmin': typeof AuthenticatedSupadminRoute
  '/authenticated/users': typeof AuthenticatedUsersRoute
  '/authenticated/site/': typeof AuthenticatedSiteIndexRoute
  '/authenticated/site/forms/$formId': typeof AuthenticatedSiteFormsFormIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/authenticated/$submissionId': typeof AuthenticatedSubmissionIdRoute
  '/authenticated/admin': typeof AuthenticatedAdminRoute
  '/authenticated/app': typeof AuthenticatedAppRoute
  '/authenticated/new': typeof AuthenticatedNewRoute
  '/authenticated/supadmin': typeof AuthenticatedSupadminRoute
  '/authenticated/users': typeof AuthenticatedUsersRoute
  '/authenticated/site': typeof AuthenticatedSiteIndexRoute
  '/authenticated/site/forms/$formId': typeof AuthenticatedSiteFormsFormIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/authenticated/$submissionId': typeof AuthenticatedSubmissionIdRoute
  '/authenticated/admin': typeof AuthenticatedAdminRoute
  '/authenticated/app': typeof AuthenticatedAppRoute
  '/authenticated/new': typeof AuthenticatedNewRoute
  '/authenticated/supadmin': typeof AuthenticatedSupadminRoute
  '/authenticated/users': typeof AuthenticatedUsersRoute
  '/authenticated/site/': typeof AuthenticatedSiteIndexRoute
  '/authenticated/site/forms/$formId': typeof AuthenticatedSiteFormsFormIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/authenticated/$submissionId'
    | '/authenticated/admin'
    | '/authenticated/app'
    | '/authenticated/new'
    | '/authenticated/supadmin'
    | '/authenticated/users'
    | '/authenticated/site/'
    | '/authenticated/site/forms/$formId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/authenticated/$submissionId'
    | '/authenticated/admin'
    | '/authenticated/app'
    | '/authenticated/new'
    | '/authenticated/supadmin'
    | '/authenticated/users'
    | '/authenticated/site'
    | '/authenticated/site/forms/$formId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/authenticated/$submissionId'
    | '/authenticated/admin'
    | '/authenticated/app'
    | '/authenticated/new'
    | '/authenticated/supadmin'
    | '/authenticated/users'
    | '/authenticated/site/'
    | '/authenticated/site/forms/$formId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthenticatedSubmissionIdRoute: typeof AuthenticatedSubmissionIdRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedSupadminRoute: typeof AuthenticatedSupadminRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedSiteIndexRoute: typeof AuthenticatedSiteIndexRoute
  AuthenticatedSiteFormsFormIdRoute: typeof AuthenticatedSiteFormsFormIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/users': {
      id: '/authenticated/users'
      path: '/authenticated/users'
      fullPath: '/authenticated/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/supadmin': {
      id: '/authenticated/supadmin'
      path: '/authenticated/supadmin'
      fullPath: '/authenticated/supadmin'
      preLoaderRoute: typeof AuthenticatedSupadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/new': {
      id: '/authenticated/new'
      path: '/authenticated/new'
      fullPath: '/authenticated/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/app': {
      id: '/authenticated/app'
      path: '/authenticated/app'
      fullPath: '/authenticated/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/admin': {
      id: '/authenticated/admin'
      path: '/authenticated/admin'
      fullPath: '/authenticated/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/$submissionId': {
      id: '/authenticated/$submissionId'
      path: '/authenticated/$submissionId'
      fullPath: '/authenticated/$submissionId'
      preLoaderRoute: typeof AuthenticatedSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/site/': {
      id: '/authenticated/site/'
      path: '/authenticated/site'
      fullPath: '/authenticated/site/'
      preLoaderRoute: typeof AuthenticatedSiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/site/forms/$formId': {
      id: '/authenticated/site/forms/$formId'
      path: '/authenticated/site/forms/$formId'
      fullPath: '/authenticated/site/forms/$formId'
      preLoaderRoute: typeof AuthenticatedSiteFormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuthenticatedSubmissionIdRoute: AuthenticatedSubmissionIdRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedSupadminRoute: AuthenticatedSupadminRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedSiteIndexRoute: AuthenticatedSiteIndexRoute,
  AuthenticatedSiteFormsFormIdRoute: AuthenticatedSiteFormsFormIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
