/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/authenticated/submissions'
import { Route as AuthenticatedAppRouteImport } from './routes/authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/authenticated/admin'
import { Route as AuthenticatedSiteIndexRouteImport } from './routes/authenticated/site.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/authenticated/admin.index'
import { Route as AuthenticatedFormsFormIdRouteImport } from './routes/authenticated/forms.$formId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/authenticated/admin.users'
import { Route as AuthenticatedAdminSubmissionsRouteImport } from './routes/authenticated/admin.submissions'
import { Route as AuthenticatedAdminSitesRouteImport } from './routes/authenticated/admin.sites'
import { Route as AuthenticatedAdminFormsRouteImport } from './routes/authenticated/admin.forms'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSiteIndexRoute = AuthenticatedSiteIndexRouteImport.update({
  id: '/site/',
  path: '/site/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedFormsFormIdRoute =
  AuthenticatedFormsFormIdRouteImport.update({
    id: '/forms/$formId',
    path: '/forms/$formId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubmissionsRoute =
  AuthenticatedAdminSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSitesRoute = AuthenticatedAdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFormsRoute = AuthenticatedAdminFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/authenticated/app': typeof AuthenticatedAppRoute
  '/authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/authenticated/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/authenticated/admin/sites': typeof AuthenticatedAdminSitesRoute
  '/authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/authenticated/forms/$formId': typeof AuthenticatedFormsFormIdRoute
  '/authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/authenticated/site/': typeof AuthenticatedSiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/authenticated/app': typeof AuthenticatedAppRoute
  '/authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/authenticated/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/authenticated/admin/sites': typeof AuthenticatedAdminSitesRoute
  '/authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/authenticated/forms/$formId': typeof AuthenticatedFormsFormIdRoute
  '/authenticated/admin': typeof AuthenticatedAdminIndexRoute
  '/authenticated/site': typeof AuthenticatedSiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/authenticated/app': typeof AuthenticatedAppRoute
  '/authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/authenticated/admin/forms': typeof AuthenticatedAdminFormsRoute
  '/authenticated/admin/sites': typeof AuthenticatedAdminSitesRoute
  '/authenticated/admin/submissions': typeof AuthenticatedAdminSubmissionsRoute
  '/authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/authenticated/forms/$formId': typeof AuthenticatedFormsFormIdRoute
  '/authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/authenticated/site/': typeof AuthenticatedSiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticated'
    | '/auth'
    | '/authenticated/admin'
    | '/authenticated/app'
    | '/authenticated/submissions'
    | '/authenticated/admin/forms'
    | '/authenticated/admin/sites'
    | '/authenticated/admin/submissions'
    | '/authenticated/admin/users'
    | '/authenticated/forms/$formId'
    | '/authenticated/admin/'
    | '/authenticated/site/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticated'
    | '/auth'
    | '/authenticated/app'
    | '/authenticated/submissions'
    | '/authenticated/admin/forms'
    | '/authenticated/admin/sites'
    | '/authenticated/admin/submissions'
    | '/authenticated/admin/users'
    | '/authenticated/forms/$formId'
    | '/authenticated/admin'
    | '/authenticated/site'
  id:
    | '__root__'
    | '/'
    | '/authenticated'
    | '/auth'
    | '/authenticated/admin'
    | '/authenticated/app'
    | '/authenticated/submissions'
    | '/authenticated/admin/forms'
    | '/authenticated/admin/sites'
    | '/authenticated/admin/submissions'
    | '/authenticated/admin/users'
    | '/authenticated/forms/$formId'
    | '/authenticated/admin/'
    | '/authenticated/site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/submissions': {
      id: '/authenticated/submissions'
      path: '/submissions'
      fullPath: '/authenticated/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/app': {
      id: '/authenticated/app'
      path: '/app'
      fullPath: '/authenticated/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/admin': {
      id: '/authenticated/admin'
      path: '/admin'
      fullPath: '/authenticated/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/site/': {
      id: '/authenticated/site/'
      path: '/site'
      fullPath: '/authenticated/site/'
      preLoaderRoute: typeof AuthenticatedSiteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/admin/': {
      id: '/authenticated/admin/'
      path: '/'
      fullPath: '/authenticated/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/authenticated/forms/$formId': {
      id: '/authenticated/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/authenticated/forms/$formId'
      preLoaderRoute: typeof AuthenticatedFormsFormIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/admin/users': {
      id: '/authenticated/admin/users'
      path: '/users'
      fullPath: '/authenticated/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/authenticated/admin/submissions': {
      id: '/authenticated/admin/submissions'
      path: '/submissions'
      fullPath: '/authenticated/admin/submissions'
      preLoaderRoute: typeof AuthenticatedAdminSubmissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/authenticated/admin/sites': {
      id: '/authenticated/admin/sites'
      path: '/sites'
      fullPath: '/authenticated/admin/sites'
      preLoaderRoute: typeof AuthenticatedAdminSitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/authenticated/admin/forms': {
      id: '/authenticated/admin/forms'
      path: '/forms'
      fullPath: '/authenticated/admin/forms'
      preLoaderRoute: typeof AuthenticatedAdminFormsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminFormsRoute: typeof AuthenticatedAdminFormsRoute
  AuthenticatedAdminSitesRoute: typeof AuthenticatedAdminSitesRoute
  AuthenticatedAdminSubmissionsRoute: typeof AuthenticatedAdminSubmissionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminFormsRoute: AuthenticatedAdminFormsRoute,
  AuthenticatedAdminSitesRoute: AuthenticatedAdminSitesRoute,
  AuthenticatedAdminSubmissionsRoute: AuthenticatedAdminSubmissionsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedFormsFormIdRoute: typeof AuthenticatedFormsFormIdRoute
  AuthenticatedSiteIndexRoute: typeof AuthenticatedSiteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedFormsFormIdRoute: AuthenticatedFormsFormIdRoute,
  AuthenticatedSiteIndexRoute: AuthenticatedSiteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
